name: Deploy - App

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        options:
          - US-Dev-App
          - EU-QA-App
          - US-QA-App
          - EU-PRD-App
          - US-PRD-App

concurrency:
  group: deploy-${{ inputs.environment }}
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy ${{ inputs.environment }}
    runs-on: ubuntu-24.04
    environment: ${{ inputs.environment }}
    steps:
      - name: Deploy
        run: echo "Deploying App into ${{ inputs.environment }}"
