name: Orchestrator - Main

on:
  workflow_dispatch:

jobs:
  pull-artifacts:
    name: Pull Artifacts
    runs-on: ubuntu-24.04
    steps:
      - name: Pull artifacts
        run: echo "[STUB] Pulling artifacts"

  deploy-us-dev-db:
    name: Deploy US-Dev-DB
    needs: pull-artifacts
    uses: ./.github/workflows/deploy-db.yml
    with:
      environment: US-Dev-DB

  deploy-us-dev-app:
    name: Deploy US-Dev-App
    needs: deploy-us-dev-db
    uses: ./.github/workflows/deploy-app.yml
    with:
      environment: US-Dev-App
